version: '3.9'

services:
  database:
    image: mongo:3.6
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  server:
    restart: on-failure
    image: parseplatform/parse-server:5.2.3
    ports:
      - 1337:1337
    environment:
      - PARSE_SERVER_APPLICATION_ID=$SERVER_APPLICATION_ID
      - PARSE_SERVER_APPLICATION_NAME=$SERVER_APPLICATION_NAME
      - PARSE_SERVER_MASTER_KEY=$SERVER_MASTER_KEY
      - PARSE_SERVER_DATABASE_URI=mongodb://admin:admin@mongo/parse_server?authSource=admin
      - PARSE_SERVER_MOUNT_GRAPHQL=true
      - PARSE_SERVER_CLOUD=/parse-server/cloud/main.js
      - PARSE_SERVER_GRAPH_QLSCHEMA=/parse-server/cloud/schema_2.graphql
    links:
      - database:mongo
    depends_on:
      - database
    volumes:
      - ./tmp/server:/data/server
      - ./parse-server/cloud:/parse-server/cloud


  dashboard:
    image: parseplatform/parse-dashboard:5.0.0
    ports:
      - "4040:4040"
    depends_on:
      - server
    environment:
      - PARSE_DASHBOARD_APP_ID=$SERVER_APPLICATION_ID
      - PARSE_DASHBOARD_MASTER_KEY=$SERVER_MASTER_KEY
      - PARSE_DASHBOARD_USER_ID=admin
      - PARSE_DASHBOARD_USER_PASSWORD=admin
      - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
      - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
      - PARSE_DASHBOARD_GRAPHQL_SERVER_URL=http://localhost:1337/graphql
    volumes:
      - ./tmp/dashboard:/data/dashboard